name: Retrain Pipeline

on:
  push:
    branches:
      - dev
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Verify workflow
        run: echo "Workflow is configured correctly"